id: apigee.googleapis.com/Proxy
$schema: gcp_schema_v_1_0.json
version: 0.0.1
technology:
  name: Google Apigee Proxy
minDynatraceVersion: 1.199
gcp:
- service: apigee.googleapis.com/Proxy
  dimensions:
  - value: resource.labels.resource_container
    id: resource_container
  - value: resource.labels.org
    id: org
  - value: resource.labels.env
    id: env
  - value: resource.labels.location
    id: location
  - value: resource.labels.proxy_name
    id: proxy_name
  - value: resource.labels.revision
    id: revision
  - value: resource.labels.host
    id: host
  metrics:
  - value: apigee.googleapis.com/policy/latencies
    id: cloud.gcp.apigee_googleapis_com.policy.latencies
    type: count,delta
    name: Apigee policy response latencies
    unit: ms
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: CUMULATIVE
    dimensions:
    - value: metric.labels.policy_name
  - value: apigee.googleapis.com/proxy/latencies
    id: cloud.gcp.apigee_googleapis_com.proxy.latencies
    type: count,delta
    name: Apigee proxy response latencies
    unit: ms
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: CUMULATIVE
    dimensions:
    - value: metric.labels.method
  - value: apigee.googleapis.com/proxy/request_count
    id: cloud.gcp.apigee_googleapis_com.proxy.request_count
    type: count,delta
    name: Apigee proxy request cumulative count
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: CUMULATIVE
    dimensions:
    - value: metric.labels.method
  - value: apigee.googleapis.com/proxy/response_count
    id: cloud.gcp.apigee_googleapis_com.proxy.response_count
    type: count,delta
    name: Apigee proxy response cumulative count
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: CUMULATIVE
    dimensions:
    - value: metric.labels.method
    - value: metric.labels.response_code
  - value: apigee.googleapis.com/target/latencies
    id: cloud.gcp.apigee_googleapis_com.target.latencies
    type: count,delta
    name: Apigee target response latencies
    unit: ms
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: CUMULATIVE
    dimensions:
    - value: metric.labels.method
    - value: metric.labels.target_type
    - value: metric.labels.target_endpoint
    - value: metric.labels.response_code
  - value: apigee.googleapis.com/target/request_count
    id: cloud.gcp.apigee_googleapis_com.target.request_count
    type: count,delta
    name: Apigee target request cumulative count
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: CUMULATIVE
    dimensions:
    - value: metric.labels.method
    - value: metric.labels.target_type
    - value: metric.labels.target_endpoint
  - value: apigee.googleapis.com/target/response_count
    id: cloud.gcp.apigee_googleapis_com.target.response_count
    type: count,delta
    name: Apigee target response cumulative count
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: CUMULATIVE
    dimensions:
    - value: metric.labels.method
    - value: metric.labels.target_type
    - value: metric.labels.target_endpoint
    - value: metric.labels.response_code
  - value: custom.googleapis.com/dynatrace/connectivity
    id: cloud.gcp.custom_googleapis_com.dynatrace.connectivity
    type: gauge
    name: Dynatrace Integration Connectivity
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.reason
    - value: metric.labels.dynatrace_tenant_url
    - value: metric.labels.function_name
  - value: custom.googleapis.com/dynatrace/ingest_lines
    id: cloud.gcp.custom_googleapis_com.dynatrace.ingest_lines
    type: gauge
    name: Dynatrace Integration Ingest Lines Count
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.status
    - value: metric.labels.dynatrace_tenant_url
    - value: metric.labels.function_name
  - value: custom.googleapis.com/dynatrace/logs_volume
    id: cloud.gcp.custom_googleapis_com.dynatrace.logs_volume
    type: count,delta
    name: Dynatrace Integration Logs Volume
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: CUMULATIVE
    dimensions:
    - value: metric.labels.status
    - value: metric.labels.function_name
  - value: custom.googleapis.com/dynatrace/phase_execution_time
    id: cloud.gcp.custom_googleapis_com.dynatrace.phase_execution_time
    type: gauge
    name: FixMe
    unit: ''
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.phase
    - value: metric.labels.dynatrace_tenant_url
    - value: metric.labels.function_name
  - value: custom.googleapis.com/dynatrace/request_count
    id: cloud.gcp.custom_googleapis_com.dynatrace.request_count
    type: gauge
    name: Dynatrace Integration Request Count
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.dynatrace_tenant_url
    - value: metric.labels.function_name
    - value: metric.labels.response_code
