id: aws_alb_load_balancer
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
technology: Google Amazon CloudFront CDN
gcp:
- service: aws_cloudfront_distribution
  dimensions:
  - value: resource.labels.project_id
    id: project_id
  - value: resource.labels.distribution_id
    id: distribution_id
  - value: resource.labels.region
    id: region
  - value: resource.labels.aws_account
    id: aws_account
  metrics:
  - value: aws.googleapis.com/CloudFront/4xxErrorRate/Average
    id: cloud.gcp.aws_googleapis_com.CloudFront.4xxErrorRate.Average
    type: gauge
    name: Average 4xx error rate
    unit: '%'
    gcpOptions:
      ingestDelay: 1200s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions: []
  - value: aws.googleapis.com/CloudFront/4xxErrorRate/Maximum
    id: cloud.gcp.aws_googleapis_com.CloudFront.4xxErrorRate.Maximum
    type: gauge
    name: Maximum 4xx error rate
    unit: '%'
    gcpOptions:
      ingestDelay: 1200s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions: []
  - value: aws.googleapis.com/CloudFront/4xxErrorRate/Minimum
    id: cloud.gcp.aws_googleapis_com.CloudFront.4xxErrorRate.Minimum
    type: gauge
    name: Minimum 4xx error rate
    unit: '%'
    gcpOptions:
      ingestDelay: 1200s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions: []
  - value: aws.googleapis.com/CloudFront/4xxErrorRate/SampleCount
    id: cloud.gcp.aws_googleapis_com.CloudFront.4xxErrorRate.SampleCount
    type: count,delta
    name: Samples of 4xx error rate
    unit: '1'
    gcpOptions:
      ingestDelay: 1200s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: DELTA
    dimensions: []
  - value: aws.googleapis.com/CloudFront/4xxErrorRate/Sum
    id: cloud.gcp.aws_googleapis_com.CloudFront.4xxErrorRate.Sum
    type: count,delta
    name: 4xx error rate
    unit: '%'
    gcpOptions:
      ingestDelay: 1200s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: DELTA
    dimensions: []
  - value: aws.googleapis.com/CloudFront/5xxErrorRate/Average
    id: cloud.gcp.aws_googleapis_com.CloudFront.5xxErrorRate.Average
    type: gauge
    name: Average 5xx error rate
    unit: '%'
    gcpOptions:
      ingestDelay: 1200s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions: []
  - value: aws.googleapis.com/CloudFront/5xxErrorRate/Maximum
    id: cloud.gcp.aws_googleapis_com.CloudFront.5xxErrorRate.Maximum
    type: gauge
    name: Maximum 5xx error rate
    unit: '%'
    gcpOptions:
      ingestDelay: 1200s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions: []
  - value: aws.googleapis.com/CloudFront/5xxErrorRate/Minimum
    id: cloud.gcp.aws_googleapis_com.CloudFront.5xxErrorRate.Minimum
    type: gauge
    name: Minimum 5xx error rate
    unit: '%'
    gcpOptions:
      ingestDelay: 1200s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions: []
  - value: aws.googleapis.com/CloudFront/5xxErrorRate/SampleCount
    id: cloud.gcp.aws_googleapis_com.CloudFront.5xxErrorRate.SampleCount
    type: count,delta
    name: Samples of 5xx error rate
    unit: '1'
    gcpOptions:
      ingestDelay: 1200s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: DELTA
    dimensions: []
  - value: aws.googleapis.com/CloudFront/5xxErrorRate/Sum
    id: cloud.gcp.aws_googleapis_com.CloudFront.5xxErrorRate.Sum
    type: count,delta
    name: 5xx error rate
    unit: '%'
    gcpOptions:
      ingestDelay: 1200s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: DELTA
    dimensions: []
  - value: aws.googleapis.com/CloudFront/BytesDownloaded/SampleCount
    id: cloud.gcp.aws_googleapis_com.CloudFront.BytesDownloaded.SampleCount
    type: count,delta
    name: Count of samples of downloaded bytes
    unit: '1'
    gcpOptions:
      ingestDelay: 1200s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: DELTA
    dimensions: []
  - value: aws.googleapis.com/CloudFront/BytesDownloaded/Sum
    id: cloud.gcp.aws_googleapis_com.CloudFront.BytesDownloaded.Sum
    type: count,delta
    name: Downloaded bytes
    unit: By
    gcpOptions:
      ingestDelay: 1200s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: DELTA
    dimensions: []
  - value: aws.googleapis.com/CloudFront/BytesUploaded/SampleCount
    id: cloud.gcp.aws_googleapis_com.CloudFront.BytesUploaded.SampleCount
    type: count,delta
    name: Count of samples of uploaded bytes
    unit: '1'
    gcpOptions:
      ingestDelay: 1200s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: DELTA
    dimensions: []
  - value: aws.googleapis.com/CloudFront/BytesUploaded/Sum
    id: cloud.gcp.aws_googleapis_com.CloudFront.BytesUploaded.Sum
    type: count,delta
    name: Uploaded bytes
    unit: By
    gcpOptions:
      ingestDelay: 1200s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: DELTA
    dimensions: []
  - value: aws.googleapis.com/CloudFront/Requests/SampleCount
    id: cloud.gcp.aws_googleapis_com.CloudFront.Requests.SampleCount
    type: count,delta
    name: Samples of request count
    unit: '1'
    gcpOptions:
      ingestDelay: 1200s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: DELTA
    dimensions: []
  - value: aws.googleapis.com/CloudFront/Requests/Sum
    id: cloud.gcp.aws_googleapis_com.CloudFront.Requests.Sum
    type: count,delta
    name: Request count
    unit: '1'
    gcpOptions:
      ingestDelay: 1200s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: DELTA
    dimensions: []
  - value: aws.googleapis.com/CloudFront/TotalErrorRate/Average
    id: cloud.gcp.aws_googleapis_com.CloudFront.TotalErrorRate.Average
    type: gauge
    name: Average error rate
    unit: '%'
    gcpOptions:
      ingestDelay: 1200s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions: []
  - value: aws.googleapis.com/CloudFront/TotalErrorRate/Maximum
    id: cloud.gcp.aws_googleapis_com.CloudFront.TotalErrorRate.Maximum
    type: gauge
    name: Maximum error rate
    unit: '%'
    gcpOptions:
      ingestDelay: 1200s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions: []
  - value: aws.googleapis.com/CloudFront/TotalErrorRate/Minimum
    id: cloud.gcp.aws_googleapis_com.CloudFront.TotalErrorRate.Minimum
    type: gauge
    name: Minimum error rate
    unit: '%'
    gcpOptions:
      ingestDelay: 1200s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions: []
  - value: aws.googleapis.com/CloudFront/TotalErrorRate/SampleCount
    id: cloud.gcp.aws_googleapis_com.CloudFront.TotalErrorRate.SampleCount
    type: count,delta
    name: Samples of error rate
    unit: '1'
    gcpOptions:
      ingestDelay: 1200s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: DELTA
    dimensions: []
  - value: aws.googleapis.com/CloudFront/TotalErrorRate/Sum
    id: cloud.gcp.aws_googleapis_com.CloudFront.TotalErrorRate.Sum
    type: count,delta
    name: Error rate
    unit: '%'
    gcpOptions:
      ingestDelay: 1200s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: DELTA
    dimensions: []