id: aws_s3_bucket
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
technology:
  name: Google Amazon S3 Bucket
gcp:
- service: aws_s3_bucket
  dimensions:
  - value: resource.labels.project_id
    id: project_id
  - value: resource.labels.bucket_name
    id: bucket_name
  - value: resource.labels.region
    id: region
  - value: resource.labels.aws_account
    id: aws_account
  metrics:
  - value: aws.googleapis.com/S3/BucketSizeBytes/Sum
    id: cloud.gcp.aws_googleapis_com.S3.BucketSizeBytes.Sum
    type: count,delta
    name: Bucket bytes
    unit: By
    gcpOptions:
      ingestDelay: 21600s
      samplePeriod: 86400s
      valueType: DOUBLE
      metricKind: DELTA
    dimensions:
    - value: metric.labels.StorageType
  - value: aws.googleapis.com/S3/NumberOfObjects/Sum
    id: cloud.gcp.aws_googleapis_com.S3.NumberOfObjects.Sum
    type: count,delta
    name: Bucket objects
    unit: '1'
    gcpOptions:
      ingestDelay: 21600s
      samplePeriod: 86400s
      valueType: DOUBLE
      metricKind: DELTA
    dimensions:
    - value: metric.labels.StorageType