id: cloudvolumesgcp-api.netapp.com/NetAppCloudVolumeSO
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
technology:
  name: Google NetApp CVS-SO
gcp:
- service: cloudvolumesgcp-api.netapp.com/NetAppCloudVolumeSO
  dimensions:
  - value: resource.labels.resource_container
    id: resource_container
  - value: resource.labels.location
    id: location
  - value: resource.labels.volume_id
    id: volume_id
  metrics:
  - value: cloudvolumesgcp-api.netapp.com/cloudvolume_so/logical_bytes_backed_up
    id: cloud.gcp.cloudvolumesgcp-api_netapp_com.cloudvolume_so.logical_bytes_backed_up
    type: gauge
    name: NetApp CVS-SO Logical Bytes Backed Up
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions: []
  - value: cloudvolumesgcp-api.netapp.com/cloudvolume_so/operation_count
    id: cloud.gcp.cloudvolumesgcp-api_netapp_com.cloudvolume_so.operation_count
    type: count,delta
    name: NetApp CVS-SO Operation Count
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.type
  - value: cloudvolumesgcp-api.netapp.com/cloudvolume_so/read_bytes_count
    id: cloud.gcp.cloudvolumesgcp-api_netapp_com.cloudvolume_so.read_bytes_count
    type: count,delta
    name: NetApp CVS-SO Read Bytes Count
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions: []
  - value: cloudvolumesgcp-api.netapp.com/cloudvolume_so/request_latencies
    id: cloud.gcp.cloudvolumesgcp-api_netapp_com.cloudvolume_so.request_latencies
    type: gauge
    name: NetApp CVS-SO Request Latencies
    unit: ms
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: DELTA
    dimensions:
    - value: metric.labels.method
  - value: cloudvolumesgcp-api.netapp.com/cloudvolume_so/volume_size
    id: cloud.gcp.cloudvolumesgcp-api_netapp_com.cloudvolume_so.volume_size
    type: gauge
    name: NetApp CVS-SO Volume Size
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions: []
  - value: cloudvolumesgcp-api.netapp.com/cloudvolume_so/volume_usage
    id: cloud.gcp.cloudvolumesgcp-api_netapp_com.cloudvolume_so.volume_usage
    type: gauge
    name: NetApp CVS-SO Volume Usage
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.type
  - value: cloudvolumesgcp-api.netapp.com/cloudvolume_so/write_bytes_count
    id: cloud.gcp.cloudvolumesgcp-api_netapp_com.cloudvolume_so.write_bytes_count
    type: count,delta
    name: NetApp CVS-SO Write Bytes Count
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions: []
  - value: custom.googleapis.com/dynatrace/connectivity
    id: cloud.gcp.custom_googleapis_com.dynatrace.connectivity
    type: gauge
    name: Dynatrace Integration Connectivity
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.reason
    - value: metric.labels.dynatrace_tenant_url
    - value: metric.labels.function_name
  - value: custom.googleapis.com/dynatrace/ingest_lines
    id: cloud.gcp.custom_googleapis_com.dynatrace.ingest_lines
    type: gauge
    name: Dynatrace Integration Ingest Lines Count
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.status
    - value: metric.labels.dynatrace_tenant_url
    - value: metric.labels.function_name
  - value: custom.googleapis.com/dynatrace/logs_volume
    id: cloud.gcp.custom_googleapis_com.dynatrace.logs_volume
    type: count,delta
    name: Dynatrace Integration Logs Volume
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: CUMULATIVE
    dimensions:
    - value: metric.labels.status
    - value: metric.labels.function_name
  - value: custom.googleapis.com/dynatrace/phase_execution_time
    id: cloud.gcp.custom_googleapis_com.dynatrace.phase_execution_time
    type: gauge
    name: FixMe
    unit: ''
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.phase
    - value: metric.labels.dynatrace_tenant_url
    - value: metric.labels.function_name
  - value: custom.googleapis.com/dynatrace/request_count
    id: cloud.gcp.custom_googleapis_com.dynatrace.request_count
    type: gauge
    name: Dynatrace Integration Request Count
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.dynatrace_tenant_url
    - value: metric.labels.function_name
    - value: metric.labels.response_code
