id: gae_instance
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
technology:
  name: Google App Engine Instance
gcp:
- service: gae_instance
  dimensions:
  - value: resource.labels.project_id
    id: project_id
  - value: resource.labels.module_id
    id: module_id
  - value: resource.labels.version_id
    id: version_id
  - value: resource.labels.instance_id
    id: instance_id
  - value: resource.labels.location
    id: location
  metrics:
  - value: appengine.googleapis.com/flex/instance/connections/current
    id: cloud.gcp.appengine_googleapis_com.flex.instance.connections.current
    type: gauge
    name: Connections
    unit: '1'
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions: []
  - value: appengine.googleapis.com/flex/instance/cpu/utilization
    id: cloud.gcp.appengine_googleapis_com.flex.instance.cpu.utilization
    type: gauge
    name: CPU Utilization
    unit: 10^2.%
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions: []
  - value: appengine.googleapis.com/flex/instance/network/received_bytes_count
    id: cloud.gcp.appengine_googleapis_com.flex.instance.network.received_bytes_count
    type: count,delta
    name: Network bytes received
    unit: By
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions: []
  - value: appengine.googleapis.com/flex/instance/network/sent_bytes_count
    id: cloud.gcp.appengine_googleapis_com.flex.instance.network.sent_bytes_count
    type: count,delta
    name: Network bytes sent
    unit: By
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions: []
  - value: appengine.googleapis.com/flex/instance/ws/avg_duration
    id: cloud.gcp.appengine_googleapis_com.flex.instance.ws.avg_duration
    type: gauge
    name: Websocket average duration
    unit: s
    gcpOptions:
      ingestDelay: 240s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions: []
  - value: custom.googleapis.com/dynatrace/connectivity
    id: cloud.gcp.custom_googleapis_com.dynatrace.connectivity
    type: gauge
    name: Dynatrace Integration Connectivity
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.reason
    - value: metric.labels.dynatrace_tenant_url
    - value: metric.labels.function_name
  - value: custom.googleapis.com/dynatrace/ingest_lines
    id: cloud.gcp.custom_googleapis_com.dynatrace.ingest_lines
    type: gauge
    name: Dynatrace Integration Ingest Lines Count
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.status
    - value: metric.labels.dynatrace_tenant_url
    - value: metric.labels.function_name
  - value: custom.googleapis.com/dynatrace/logs_volume
    id: cloud.gcp.custom_googleapis_com.dynatrace.logs_volume
    type: count,delta
    name: Dynatrace Integration Logs Volume
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: CUMULATIVE
    dimensions:
    - value: metric.labels.status
    - value: metric.labels.function_name
  - value: custom.googleapis.com/dynatrace/phase_execution_time
    id: cloud.gcp.custom_googleapis_com.dynatrace.phase_execution_time
    type: gauge
    name: FixMe
    unit: ''
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.phase
    - value: metric.labels.dynatrace_tenant_url
    - value: metric.labels.function_name
  - value: custom.googleapis.com/dynatrace/request_count
    id: cloud.gcp.custom_googleapis_com.dynatrace.request_count
    type: gauge
    name: Dynatrace Integration Request Count
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.dynatrace_tenant_url
    - value: metric.labels.function_name
    - value: metric.labels.response_code
