id: gce_zone_network_health
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
technology:
  name: Google Zone Network Health
gcp:
- service: gce_zone_network_health
  featureSet: default
  dimensions:
  - value: resource.labels.project_id
    id: project_id
  - value: resource.labels.zone
    id: zone
  - value: resource.labels.region
    id: region
  metrics:
  - value: networking.googleapis.com/cloud_netslo/active_probing/probe_count
    id: cloud.gcp.networking_googleapis_com.cloud_netslo.active_probing.probe_count
    type: count,delta
    name: Number of probes
    unit: '1'
    gcpOptions:
      ingestDelay: 420s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.remote_zone
    - value: metric.labels.remote_region
    - value: metric.labels.remote_location_type
    - value: metric.labels.protocol
    - value: metric.labels.result
