id: iam_service_account
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
technology:
  name: Google IAM Service Account
gcp:
- service: iam_service_account
  dimensions:
  - value: resource.labels.project_id
    id: project_id
  - value: resource.labels.unique_id
    id: unique_id
  metrics:
  - value: iam.googleapis.com/service_account/authn_events_count
    id: cloud.gcp.iam_googleapis_com.service_account.authn_events_count
    type: count,delta
    name: Authentication Events
    unit: '1'
    gcpOptions:
      ingestDelay: 10800s
      samplePeriod: 600s
      valueType: INT64
      metricKind: DELTA
    dimensions: []
  - value: iam.googleapis.com/service_account/key/authn_events_count
    id: cloud.gcp.iam_googleapis_com.service_account.key.authn_events_count
    type: count,delta
    name: Key Authentication Events
    unit: '1'
    gcpOptions:
      ingestDelay: 10800s
      samplePeriod: 600s
      valueType: INT64
      metricKind: DELTA
    dimensions:
    - value: metric.labels.key_id
