id: recaptchaenterprise.googleapis.com/Key
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
technology:
  name: Google reCAPTCHA Key
gcp:
- service: recaptchaenterprise.googleapis.com/Key
  dimensions:
  - value: resource.labels.resource_container
    id: resource_container
  - value: resource.labels.location
    id: location
  - value: resource.labels.key_id
    id: key_id
  metrics:
  - value: custom.googleapis.com/dynatrace/connectivity
    id: cloud.gcp.custom_googleapis_com.dynatrace.connectivity
    type: gauge
    name: Dynatrace Integration Connectivity
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.reason
    - value: metric.labels.dynatrace_tenant_url
    - value: metric.labels.function_name
  - value: custom.googleapis.com/dynatrace/ingest_lines
    id: cloud.gcp.custom_googleapis_com.dynatrace.ingest_lines
    type: gauge
    name: Dynatrace Integration Ingest Lines Count
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.status
    - value: metric.labels.dynatrace_tenant_url
    - value: metric.labels.function_name
  - value: custom.googleapis.com/dynatrace/logs_volume
    id: cloud.gcp.custom_googleapis_com.dynatrace.logs_volume
    type: count,delta
    name: Dynatrace Integration Logs Volume
    unit: By
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: CUMULATIVE
    dimensions:
    - value: metric.labels.status
    - value: metric.labels.function_name
  - value: custom.googleapis.com/dynatrace/phase_execution_time
    id: cloud.gcp.custom_googleapis_com.dynatrace.phase_execution_time
    type: gauge
    name: FixMe
    unit: ''
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DOUBLE
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.phase
    - value: metric.labels.dynatrace_tenant_url
    - value: metric.labels.function_name
  - value: custom.googleapis.com/dynatrace/request_count
    id: cloud.gcp.custom_googleapis_com.dynatrace.request_count
    type: gauge
    name: Dynatrace Integration Request Count
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: INT64
      metricKind: GAUGE
    dimensions:
    - value: metric.labels.dynatrace_tenant_url
    - value: metric.labels.function_name
    - value: metric.labels.response_code
  - value: recaptchaenterprise.googleapis.com/score_counts
    id: cloud.gcp.recaptchaenterprise_googleapis_com.score_counts
    type: gauge
    name: Score counts
    unit: '1'
    gcpOptions:
      ingestDelay: 180s
      samplePeriod: 60s
      valueType: DISTRIBUTION
      metricKind: DELTA
    dimensions:
    - value: metric.labels.action
