id: transfer_service_agent
$schema: gcp_schema_v_1_0.json
version: 0.0.1
minDynatraceVersion: 1.199
technology:
  name: Google Transfer Service Agent
gcp:
- service: transfer_service_agent
  dimensions:
  - value: resource.labels.project_id
    id: project_id
  - value: resource.labels.agent_id
    id: agent_id
  metrics:
  - value: storagetransfer.googleapis.com/agent/connected
    id: cloud.gcp.storagetransfer_googleapis_com.agent.connected
    type: gauge
    name: Agent connected status
    unit: ''
    gcpOptions:
      ingestDelay: 60s
      samplePeriod: 60s
      valueType: BOOL
      metricKind: GAUGE
    dimensions: []
  - value: storagetransfer.googleapis.com/agent/transferred_bytes_count
    id: cloud.gcp.storagetransfer_googleapis_com.agent.transferred_bytes_count
    type: count,delta
    name: Agent transfer delta
    unit: By
    gcpOptions:
      ingestDelay: 60s
      samplePeriod: 60s
      valueType: INT64
      metricKind: DELTA
    dimensions: []
